name:                parking
version:             0.1.0
github:              "jihygk/parking"
license:             BSD3
author:              "Jay Kim"
maintainer:          "jihygk@gmail.com"
copyright:           "2019 Jay Kim"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/parking#readme>

dependencies:
- aeson
- amazonka
- amazonka-s3
- base >= 4.7 && < 5
- bytestring
- iso8601-time
- lens
- lens-aeson
- serverless-haskell
- text
- time
- wreq


library:
  source-dirs: src

executables:
  parking-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parking

tests:
  parking-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parking
